model = "gpt-5.4"
model_reasoning_effort = "xhigh"
[projects."/Users/harry/repo/ai-plays-slay-the-spire"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"

[sandbox_workspace_write]
network_access = true
writable_roots = [
    "/Users/harry/.cache/uv",
    "/Users/harry/repo/ai-plays-slay-the-spire",
]
